// src/components/ProfileCard.tsx
import { defineComponent } from "vue";

export default defineComponent({
  name: "ProfileCard",
  props: {
    className: { type: String, required: false },
  },
  setup(props) {
    return () => (
      <div
        class={[
          "bg-white/10 backdrop-blur-[10px] border border-white/20 rounded-[16px] p-8 text-white shadow-[0_4px_30px_rgba(0,0,0,0.1)]",
          props.className,
        ]}
      >
        <div>
          <div>
            <img
              src="https://github.com/MiyakoMeow.png"
              alt="Miyako Meow"
              class="w-[120px] h-[120px] rounded-full border-[4px] border-white/30 mb-4 shadow-[0_0_20px_rgba(255,255,255,0.2)] transition-transform duration-300 hover:scale-105 hover:rotate-[5deg]"
            />
          </div>
          <h1
            class="my-2 text-[2.5rem] bg-clip-text text-transparent"
            style={{
              background: "linear-gradient(90deg,#a78bfa,#f472b6,#60a5fa)",
              WebkitBackgroundClip: "text",
              WebkitTextFillColor: "transparent",
            }}
          >
            MiyakoMeow
          </h1>
          <p class="text-[#a5b4fc] text-[1.1rem] mb-8">一个天天摸鱼的大学生。</p>
        </div>

        <div class="mb-10 leading-[1.6] text-white/90">
          <p>欢迎来到我的个人主页！</p>
        </div>

        <div class="flex gap-4 justify-center flex-wrap">
          <a
            href="https://github.com/MiyakoMeow"
            target="_blank"
            class="px-[1.5rem] py-[0.8rem] bg-white/10 border border-white/20 rounded-[50px] text-white no-underline font-medium transition-all duration-300 ease-in-out hover:bg-white/20 hover:shadow-[0_5px_15px_rgba(0,0,0,0.2)] hover:-translate-y-0.5"
          >
            {" "}
            GitHub{" "}
          </a>
          <a
            href="https://space.bilibili.com/215242890"
            class="px-[1.5rem] py-[0.8rem] bg-white/10 border border-white/20 rounded-[50px] text-white no-underline font-medium transition-all duration-300 ease-in-out hover:bg-white/20 hover:shadow-[0_5px_15px_rgba(0,0,0,0.2)] hover:-translate-y-0.5"
          >
            {" "}
            Bilibili{" "}
          </a>
          <a
            href="https://x.com/MiyakoWoW"
            class="px-[1.5rem] py-[0.8rem] bg-white/10 border border-white/20 rounded-[50px] text-white no-underline font-medium transition-all duration-300 ease-in-out hover:bg-white/20 hover:shadow-[0_5px_15px_rgba(0,0,0,0.2)] hover:-translate-y-0.5"
          >
            {" "}
            X{" "}
          </a>
        </div>
      </div>
    );
  },
});

// src/lib/components/ProfileCard.svelte
<script lang="ts">
  import FloatingPanel from "./FloatingPanel.svelte";
</script>

<FloatingPanel
  sessionKey="miyakomeow_profile_card_seen"
  initiallyOpen={true}
  position="top-left"
  size="large"
  ariaLabel="个人信息卡片"
>
  {#snippet icon()}
    <img
      class="size-11 rounded-full border-2 border-white/30"
      src="https://github.com/MiyakoMeow.png"
      alt="Miyako Meow"
    />
  {/snippet}

  <div class="text-center">
    <div>
      <div>
        <img
          class="mx-auto mb-4 h-30 w-30 rounded-full border-4 border-white/30 shadow-[0_0_20px_rgba(255,255,255,0.2)] transition-transform duration-300 ease-in-out hover:scale-105 hover:rotate-[5deg]"
          src="https://github.com/MiyakoMeow.png"
          alt="Miyako Meow"
        />
      </div>
      <h1
        class="my-2 bg-[linear-gradient(90deg,#a78bfa,#f472b6,#60a5fa)] bg-clip-text text-[2.5rem] text-transparent"
      >
        MiyakoMeow
      </h1>
      <p class="mb-8 text-[1.1rem] text-[#a5b4fc]">喵喵喵！</p>
    </div>

    <div class="mb-10 leading-[1.6] text-white/90">
      <p>追逐成就感中</p>
    </div>

    <div class="flex flex-wrap justify-center gap-4">
      <a
        href="https://github.com/MiyakoMeow"
        target="_blank"
        class="rounded-[50px] border border-white/20 bg-white/10 px-6 py-[0.8rem] font-medium text-white no-underline transition-all duration-300 ease-in-out hover:-translate-y-0.5 hover:bg-white/20 hover:shadow-[0_5px_15px_rgba(0,0,0,0.2)]"
      >
        GitHub
      </a>
      <a
        href="https://space.bilibili.com/215242890"
        class="rounded-[50px] border border-white/20 bg-white/10 px-6 py-[0.8rem] font-medium text-white no-underline transition-all duration-300 ease-in-out hover:-translate-y-0.5 hover:bg-white/20 hover:shadow-[0_5px_15px_rgba(0,0,0,0.2)]"
      >
        Bilibili
      </a>
      <a
        href="https://x.com/MiyakoWoW"
        class="rounded-[50px] border border-white/20 bg-white/10 px-6 py-[0.8rem] font-medium text-white no-underline transition-all duration-300 ease-in-out hover:-translate-y-0.5 hover:bg-white/20 hover:shadow-[0_5px_15px_rgba(0,0,0,0.2)]"
      >
        X (Twitter)
      </a>
    </div>
  </div>
</FloatingPanel>
