// src/layout/BlogLayout.tsx
import { defineComponent } from "vue";
import StarryBackground from "../components/StarryBackground";
import ProfileCard from "../components/ProfileCard";

export default defineComponent({
  name: "BlogLayout",
  setup(_, { slots }) {
    return () => (
      <>
        <StarryBackground />
        <main class="grid grid-cols-[380px_1fr] gap-8 items-start max-w-[1400px] m-0 mx-auto p-8 w-full box-border">
          <aside class="flex justify-center w-full mt-8">
            <ProfileCard className="max-w-[360px] w-full animate-fadeIn m-0 mx-auto block" />
          </aside>
          <section class="w-full">{slots.default?.()}</section>
        </main>
      </>
    );
  },
});

// src/layout/BlogLayout.svelte
<script lang="ts">
  import StarryBackground from "../components/StarryBackground.svelte";
  import ProfileCard from "../components/ProfileCard.svelte";
</script>

<StarryBackground />
<main
  class="m-0 mx-auto box-border grid w-full max-w-350 grid-cols-[380px_1fr] items-start gap-8 p-8"
>
  <aside class="mt-8 flex w-full justify-center">
    <div class="m-0 mx-auto block w-full max-w-90 animate-fadeIn">
      <ProfileCard />
    </div>
  </aside>
  <section class="w-full">
    <slot />
  </section>
</main>
